adminTva:
    pattern:  /
    defaults: { _controller: "EcommerceBundle:TvaAdmin:index" }

adminTva_show:
    pattern:  /{id}/show
    defaults: { _controller: "EcommerceBundle:TvaAdmin:show" }

adminTva_new:
    pattern:  /new
    defaults: { _controller: "EcommerceBundle:TvaAdmin:new" }

adminTva_create:
    pattern:  /create
    defaults: { _controller: "EcommerceBundle:TvaAdmin:create" }
    requirements: { _method: post }

adminTva_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EcommerceBundle:TvaAdmin:edit" }

adminTva_update:
    pattern:  /{id}/update
    defaults: { _controller: "EcommerceBundle:TvaAdmin:update" }
    requirements: { _method: post|put }

adminTva_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EcommerceBundle:TvaAdmin:delete" }
    requirements: { _method: post|delete }
